from typing import Protocol, runtime_checkable


@runtime_checkable
class Healer(Protocol):
    def attack(self) -> str: ...
    def heal(self) -> str: ...
    def describe(self) -> str: ...


@runtime_checkable
class Transformer(Protocol):
    def attack(self) -> str: ...
    def describe(self) -> str: ...
    def transform(self) -> str: ...
    def revert(self) -> str: ...
